config/routes.rb
Rails.application.routes.draw do

  resources :settings
  resources :social_links
  resources :map_tiles_subscriptions
  resources :map_tiles
  resources :map_categories
  resources :maps
  resources :likes
  resources :mentions
  resources :icons
  resources :notes
  resources :notifications
  resources :links
  resources :space_subscriptions
  resources :documents
  resources :comments
  resources :posts
  resources :spaces
  resources :space_types
  resources :participants
  resources :messages
  devise_for :users
    root 'pages#profile'

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/discussion.rb
class Discussion < ApplicationRecord
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/icon.rb
class Icon < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :user
end

app/models/map.rb
class Map < ApplicationRecord
  belongs_to :user
end

app/models/map_category.rb
class MapCategory < ApplicationRecord
end

app/models/map_tile.rb
class MapTile < ApplicationRecord
  belongs_to :map
  belongs_to :map_category
  belongs_to :user
end

app/models/mention.rb
class Mention < ApplicationRecord
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :discussion
  belongs_to :user
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :discussion
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord

    # Relationships
    belongs_to :space
    belongs_to :user
end

app/models/setting.rb
class Setting < ApplicationRecord
end

app/models/social_link.rb
class SocialLink < ApplicationRecord

    # Relationships
    belongs_to :user
    
end

app/models/space.rb
class Space < ApplicationRecord

    # Relationships
    belongs_to :user
    has_many :posts
end

app/models/space_type.rb
class SpaceType < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable, :timeoutable, :omniauthable

  # Relationships
  has_many :posts
  has_many :comments
  has_many :social_links
  has_many :spaces

  # Validations

end

app/controllers/social_links_controller.rb
class SocialLinksController < ApplicationController
  before_action :set_social_link, only: [:show, :edit, :update, :destroy]

  # GET /social_links
  # GET /social_links.json
  def index
    @social_links = SocialLink.all
  end

  # GET /social_links/1
  # GET /social_links/1.json
  def show
  end

  # GET /social_links/new
  def new
    @social_link = SocialLink.new
  end

  # GET /social_links/1/edit
  def edit
  end

  # POST /social_links
  # POST /social_links.json
  def create
    @social_link = SocialLink.new(social_link_params)

    respond_to do |format|
      if @social_link.save
        format.html { redirect_to @social_link, notice: 'Social link was successfully created.' }
        format.json { render :show, status: :created, location: @social_link }
      else
        format.html { render :new }
        format.json { render json: @social_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /social_links/1
  # PATCH/PUT /social_links/1.json
  def update
    respond_to do |format|
      if @social_link.update(social_link_params)
        format.html { redirect_to @social_link, notice: 'Social link was successfully updated.' }
        format.json { render :show, status: :ok, location: @social_link }
      else
        format.html { render :edit }
        format.json { render json: @social_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /social_links/1
  # DELETE /social_links/1.json
  def destroy
    @social_link.destroy
    respond_to do |format|
      format.html { redirect_to social_links_url, notice: 'Social link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_social_link
      @social_link = SocialLink.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def social_link_params
      params.require(:social_link).permit(:user_id, :title, :url)
    end
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/social_links_helper.rb
module SocialLinksHelper
end

app/views/social_links/_form.html.erb
<%= form_for(social_link) do |f| %>
  <% if social_link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(social_link.errors.count, "error") %> prohibited this social_link from being saved:</h2>

      <ul>
      <% social_link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/social_links/edit.html.erb
<h1>Editing Social Link</h1>

<%= render 'form', social_link: @social_link %>

<%= link_to 'Show', @social_link %> |
<%= link_to 'Back', social_links_path %>

app/views/social_links/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Social Links</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Title</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @social_links.each do |social_link| %>
      <tr>
        <td><%= social_link.user %></td>
        <td><%= social_link.title %></td>
        <td><%= social_link.url %></td>
        <td><%= link_to 'Show', social_link %></td>
        <td><%= link_to 'Edit', edit_social_link_path(social_link) %></td>
        <td><%= link_to 'Destroy', social_link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Social Link', new_social_link_path %>

app/views/social_links/new.html.erb
<h1>New Social Link</h1>

<%= render 'form', social_link: @social_link %>

<%= link_to 'Back', social_links_path %>

app/views/social_links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @social_link.user %>
</p>

<p>
  <strong>Title:</strong>
  <%= @social_link.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @social_link.url %>
</p>

<%= link_to 'Edit', edit_social_link_path(@social_link) %> |
<%= link_to 'Back', social_links_path %>