config/routes.rb
Rails.application.routes.draw do

  resources :settings
  resources :social_links
  resources :map_tiles_subscriptions
  resources :map_tiles
  resources :map_categories
  resources :maps
  resources :likes
  resources :mentions
  resources :icons
  resources :notes
  resources :notifications
  resources :links
  resources :space_subscriptions
  resources :documents
  resources :comments
  resources :posts
  resources :spaces
  resources :space_types
  resources :participants
  resources :messages
  devise_for :users
    root 'pages#profile'

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/discussion.rb
class Discussion < ApplicationRecord
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/icon.rb
class Icon < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :user
end

app/models/map.rb
class Map < ApplicationRecord
  belongs_to :user
end

app/models/map_category.rb
class MapCategory < ApplicationRecord
end

app/models/map_tile.rb
class MapTile < ApplicationRecord
  belongs_to :map
  belongs_to :map_category
  belongs_to :user
end

app/models/mention.rb
class Mention < ApplicationRecord
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :discussion
  belongs_to :user
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :discussion
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord

    # Relationships
    belongs_to :space
    belongs_to :user
end

app/models/setting.rb
class Setting < ApplicationRecord
end

app/models/social_link.rb
class SocialLink < ApplicationRecord

    # Relationships
    belongs_to :user
    
end

app/models/space.rb
class Space < ApplicationRecord

    # Relationships
    belongs_to :user
    has_many :posts
end

app/models/space_type.rb
class SpaceType < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable, :timeoutable, :omniauthable

  # Relationships
  has_many :posts
  has_many :comments
  has_many :social_links
  has_many :spaces

  # Validations

end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_action :set_map, only: [:show, :edit, :update, :destroy]

  # GET /maps
  # GET /maps.json
  def index
    @maps = Map.all
  end

  # GET /maps/1
  # GET /maps/1.json
  def show
  end

  # GET /maps/new
  def new
    @map = Map.new
  end

  # GET /maps/1/edit
  def edit
  end

  # POST /maps
  # POST /maps.json
  def create
    @map = Map.new(map_params)

    respond_to do |format|
      if @map.save
        format.html { redirect_to @map, notice: 'Map was successfully created.' }
        format.json { render :show, status: :created, location: @map }
      else
        format.html { render :new }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maps/1
  # PATCH/PUT /maps/1.json
  def update
    respond_to do |format|
      if @map.update(map_params)
        format.html { redirect_to @map, notice: 'Map was successfully updated.' }
        format.json { render :show, status: :ok, location: @map }
      else
        format.html { render :edit }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maps/1
  # DELETE /maps/1.json
  def destroy
    @map.destroy
    respond_to do |format|
      format.html { redirect_to maps_url, notice: 'Map was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_map
      @map = Map.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def map_params
      params.require(:map).permit(:user_id, :title, :active)
    end
end

app/helpers/icons_helper.rb
module IconsHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/maps/_form.html.erb
<%= form_for(map) do |f| %>
  <% if map.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(map.errors.count, "error") %> prohibited this map from being saved:</h2>

      <ul>
      <% map.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :active %>
    <%= f.check_box :active %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/maps/edit.html.erb
<h1>Editing Map</h1>

<%= render 'form', map: @map %>

<%= link_to 'Show', @map %> |
<%= link_to 'Back', maps_path %>

app/views/maps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Maps</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Title</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @maps.each do |map| %>
      <tr>
        <td><%= map.user %></td>
        <td><%= map.title %></td>
        <td><%= map.active %></td>
        <td><%= link_to 'Show', map %></td>
        <td><%= link_to 'Edit', edit_map_path(map) %></td>
        <td><%= link_to 'Destroy', map, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Map', new_map_path %>

app/views/maps/new.html.erb
<h1>New Map</h1>

<%= render 'form', map: @map %>

<%= link_to 'Back', maps_path %>

app/views/maps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @map.user %>
</p>

<p>
  <strong>Title:</strong>
  <%= @map.title %>
</p>

<p>
  <strong>Active:</strong>
  <%= @map.active %>
</p>

<%= link_to 'Edit', edit_map_path(@map) %> |
<%= link_to 'Back', maps_path %>