config/routes.rb
Rails.application.routes.draw do

  resources :settings
  resources :social_links
  resources :map_tiles_subscriptions
  resources :map_tiles
  resources :map_categories
  resources :maps
  resources :likes
  resources :mentions
  resources :icons
  resources :notes
  resources :notifications
  resources :links
  resources :space_subscriptions
  resources :documents
  resources :comments
  resources :posts
  resources :spaces
  resources :space_types
  resources :participants
  resources :messages
  devise_for :users
    root 'pages#profile'

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/discussion.rb
class Discussion < ApplicationRecord
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/icon.rb
class Icon < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :user
end

app/models/map.rb
class Map < ApplicationRecord
  belongs_to :user
end

app/models/map_category.rb
class MapCategory < ApplicationRecord
end

app/models/map_tile.rb
class MapTile < ApplicationRecord
  belongs_to :map
  belongs_to :map_category
  belongs_to :user
end

app/models/mention.rb
class Mention < ApplicationRecord
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :discussion
  belongs_to :user
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :discussion
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord

    # Relationships
    belongs_to :space
    belongs_to :user
end

app/models/setting.rb
class Setting < ApplicationRecord
end

app/models/social_link.rb
class SocialLink < ApplicationRecord

    # Relationships
    belongs_to :user
    
end

app/models/space.rb
class Space < ApplicationRecord

    # Relationships
    belongs_to :user
    has_many :posts
end

app/models/space_type.rb
class SpaceType < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable, :timeoutable, :omniauthable

  # Relationships
  has_many :posts
  has_many :comments
  has_many :social_links
  has_many :spaces

  # Validations

end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :set_notification, only: [:show, :edit, :update, :destroy]

  # GET /notifications
  # GET /notifications.json
  def index
    @notifications = Notification.all
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def show
  end

  # GET /notifications/new
  def new
    @notification = Notification.new
  end

  # GET /notifications/1/edit
  def edit
  end

  # POST /notifications
  # POST /notifications.json
  def create
    @notification = Notification.new(notification_params)

    respond_to do |format|
      if @notification.save
        format.html { redirect_to @notification, notice: 'Notification was successfully created.' }
        format.json { render :show, status: :created, location: @notification }
      else
        format.html { render :new }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notifications/1
  # PATCH/PUT /notifications/1.json
  def update
    respond_to do |format|
      if @notification.update(notification_params)
        format.html { redirect_to @notification, notice: 'Notification was successfully updated.' }
        format.json { render :show, status: :ok, location: @notification }
      else
        format.html { render :edit }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @notification.destroy
    respond_to do |format|
      format.html { redirect_to notifications_url, notice: 'Notification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = Notification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notification_params
      params.require(:notification).permit(:title, :user_id, :active, :last_read, :table_name, :table_id, :link, :category)
    end
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.erb
<%= form_for(notification) do |f| %>
  <% if notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
      <% notification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :active %>
    <%= f.check_box :active %>
  </div>

  <div class="field">
    <%= f.label :last_read %>
    <%= f.datetime_select :last_read %>
  </div>

  <div class="field">
    <%= f.label :table_name %>
    <%= f.text_field :table_name %>
  </div>

  <div class="field">
    <%= f.label :table_id %>
    <%= f.number_field :table_id %>
  </div>

  <div class="field">
    <%= f.label :link %>
    <%= f.text_field :link %>
  </div>

  <div class="field">
    <%= f.label :category %>
    <%= f.text_field :category %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notifications/edit.html.erb
<h1>Editing Notification</h1>

<%= render 'form', notification: @notification %>

<%= link_to 'Show', @notification %> |
<%= link_to 'Back', notifications_path %>

app/views/notifications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notifications</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>User</th>
      <th>Active</th>
      <th>Last read</th>
      <th>Table name</th>
      <th>Table</th>
      <th>Link</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notifications.each do |notification| %>
      <tr>
        <td><%= notification.title %></td>
        <td><%= notification.user %></td>
        <td><%= notification.active %></td>
        <td><%= notification.last_read %></td>
        <td><%= notification.table_name %></td>
        <td><%= notification.table_id %></td>
        <td><%= notification.link %></td>
        <td><%= notification.category %></td>
        <td><%= link_to 'Show', notification %></td>
        <td><%= link_to 'Edit', edit_notification_path(notification) %></td>
        <td><%= link_to 'Destroy', notification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notification', new_notification_path %>

app/views/notifications/new.html.erb
<h1>New Notification</h1>

<%= render 'form', notification: @notification %>

<%= link_to 'Back', notifications_path %>

app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @notification.title %>
</p>

<p>
  <strong>User:</strong>
  <%= @notification.user %>
</p>

<p>
  <strong>Active:</strong>
  <%= @notification.active %>
</p>

<p>
  <strong>Last read:</strong>
  <%= @notification.last_read %>
</p>

<p>
  <strong>Table name:</strong>
  <%= @notification.table_name %>
</p>

<p>
  <strong>Table:</strong>
  <%= @notification.table_id %>
</p>

<p>
  <strong>Link:</strong>
  <%= @notification.link %>
</p>

<p>
  <strong>Category:</strong>
  <%= @notification.category %>
</p>

<%= link_to 'Edit', edit_notification_path(@notification) %> |
<%= link_to 'Back', notifications_path %>